title: Pooran Chandrashekaraiah # your name (or website title) here
logo: "/images/IMG-20181215-WA0022.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Application Developer</b>
  <br><br>
 
  <br><br>
  <a href="https://www.linkedin.com/in/pooran-chandrashekharaiah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
