title: Pooran Chandrashekaraiah # your name (or website title) here
logo: "/images/IMG-20181215-WA0022.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Application Developer
  <br><br>
  First and foremost, I love programming. I still remember, 
  when I was first introduced to object-oriented programming in bachelor's, 
  I was quite intrigued by how problems could be solved through the ideas of objects, inheritance, and abstraction. 
  Software engineering is a never-ending puzzle and I'm committed to solving it passionately. 
  I think programming helps transmit our ideas in a structured and logical manner to solve a particular problem.
  
  For my first professional contract, I was given the opportunity to be part of complete software development life cycle, 
  from creating a technical requirement, software coding phase till testing phase, 
  which was e-commerce website in java/j2ee for Hewlett Packard. 
  Later moved towards server maintenance and code deployment. Further, into Agile software development, 
  Today I am an application developer at Fenecon Gmbh, developing controllers and 
  devices which are controlled by these controllers in Energy management service(EMS).

I tend to read data science blogs, machine learning (interest and curiosity that I picked up in my Master's studies) 
and write code at home after office hours. 
In free time, I follow Football leagues and get inspired by the hard work players put day-in-day-out of their careers, 
which challenges me in many aspects such as teamwork, hard work, organization, problem-solving. 
This is what keeps me up at night, the never-ending thirst to learn and share it others.  
  <br><br>
  <a href="https://www.linkedin.com/in/pooran-chandrashekharaiah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
