title: Pooran Chandrashekaraiah # your name (or website title) here
logo: "/images/capture-capture.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Senior Software Engineer</b>
  <br><br>
 <p></p>
  <br><br>
  <a href="https://www.linkedin.com/in/pooran-chandrashekharaiah/">View My LinkedIn Profile</a> 
  <a href="https://github.com/pooran-c">Github account</a> 
  <a href="https://github.com/pooranc">Github account</a> 
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-177943286-1 # your Google Analytics tracking ID here
